import { NextPage } from 'next';
import {Kv} from '../components/TopPage/kv';
import {Komafes} from '../components/TopPage/komafes';
import {Concept} from '../components/TopPage/concept';
import {Projects} from '../components/TopPage/projects';
import {Footer} from '../components/Footer';
import Head from 'next/head';
import styles from '../styles/pages/Home.module.scss';

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>ゆらぎ | designing plus nine</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Kv/>
    <Concept/>
    <Projects/>
    <Komafes/>
    <Footer></Footer>
  </div>
);

export default Home;
