import { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/pages/Home.module.scss';

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>ゆらぎ | designing plus nine</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <h1 className={styles.title}>Welcome to Komaba Festival exhibition by designing plus nine!</h1>
  </div>
);

export default Home;
